### ISSUE TITLE
Adição de nova base de dados

### ISSUE THREAD

**Issue by alexandrefazenda** [msperlin/GetTDData#1]
Adição de nova base de dados da Anbima - Estrutura a Termo das Taxas de Juros Estimada.

https://www.anbima.com.br/informacoes/est-termo/CZ.asp

**Comment by msperlin** [comment]
Alexandre, acabei de arrumar a função. Anova versão já está aqui no github. A versão do CRAN está encaminhada e deve atualizar para todos em alguns dias. 

At,
