### ISSUE TITLE
bizdays::holidaysANBIMA is no longer available

### ISSUE THREAD

**Issue by wilsonfreitas** [msperlin/GetTDData#10]
The list of holidays `bizdays::holidaysANBIMA` is no longer available and has impact on this GetTDData.

```
Changes to worse in reverse depends:

Package: GetTDData
Check: dependencies in R code
New result: WARNING
  Missing or unexported object: ‘bizdays::holidaysANBIMA’
```

Now the calendars have to be loaded by calling `bizdays::load_builtin_calendars()` and the ANBIMA's holidays can be acessed this way:

```r
cal <- bizdays::calendars()[["Brazil/ANBIMA"]]
cal$holidays
```

**Comment by msperlin** [comment]
Thanks Wilson!

**Comment by msperlin** [comment]
Are these changes on CRAN?

**Comment by msperlin** [comment]
I just checked and it is not in CRAN. The gettdata pkg is working with the cran version..

**Comment by wilsonfreitas** [comment]
Hi!
The package is on its way to CRAN.
This warning has shown up along the process.

I've implemented an old change to load the calendars from a JSON file, so that they become portable.
As a consequence the holidays* in data are no longer necessary 🤷‍♂️.

**Comment by msperlin** [comment]
Thanks. I'm submitting a patch right now.
