### ISSUE TITLE
Novo título TD: RENDA+

### ISSUE THREAD

**Issue by andreltr** [msperlin/GetTDData#13]
Olá,

O novo título do TD: RENDA+ está implementado?  
Caso positivo, qual é seu código? 
Caso negativo, está em plano implementa-lo?

Atenciosamente,

--
André Luiz Tietböhl Ramos, Dr.

**Comment by msperlin** [comment]
Oi André,

Segue abaixo:

> O novo título do TD: RENDA+ está implementado?

Nao.

> Caso negativo, está em plano implementa-lo?

No curto prazo, não. Como sabes, o título começou a ser negociado em jan 2023. A quantidade de dados é muito pequeno neste momento.

Abc.
