### ISSUE TITLE
Dúvida sobre a lista de títulos baixada de forma diferente da disponibilidade atual

### ISSUE THREAD

**Issue by andreltr** [msperlin/GetTDData#14]
Olá,

Eu tenho utilizado GetTDData para baixar os dados do TD.  Entretanto, eu verifico que os dados baixados diferem do reportado pelo site.  Senão vejamos para 24/06/2023 e, por exemplo, LTN.  O site do TD informa como disponíveis para compra os seguintes títulos: LTN 20260101, LTN 20290101 e LTN 20330101.

Eu desenvolvi uma função R, abaixo, para retornar uma lista dos títulos TD disponíveis e ela retorna dados díspares do informado.

Um exemplo de código, com a função, está abaixo:  

titulo.td <- get.td(titulo)
## designação de todas maturidades de título LTN para um data frame
LTN.df <- titulo.td

LTN.df$ref.date <- as.Date(LTN.df$ref.date)

maturidades.validas <- get.matur(titulo, titulo.td)

R> [1] "Maturidades validas para o titulo LTN na ultima data util corrente/hoje: 2023-06-23"
    ref.date yield.bid price.bid asset.code matur.date
1 2023-06-23   11.8700    893.09 LTN 010724 2024-07-01
2 2023-06-23   11.0600    852.27 LTN 010125 2025-01-01
3 2023-06-23   10.5100    776.76 LTN 010126 2026-01-01
4 2023-06-23   10.8600    566.97 LTN 010129 2029-01-01

Ou seja, o output da função get.matur() difere do reportado pelo site, como já expresso.  Este 
fato seria devido a uma filtragem errada utilizando a biblioteca lubridate?
Um segundo aspecto interessante é que o output dessa função retorna LTN 010724, que não está disponível, e não retorna LTN 20330101, que está.

message("Ultimos valores do titulo ", titulo,":") 
tail(titulo.td, 10)

R> tail(titulo.td, 10)
        ref.date yield.bid price.bid asset.code matur.date
23912 2023-06-12    0.1090    563.75 LTN 010129 2029-01-01
23913 2023-06-13    0.1103    560.34 LTN 010129 2029-01-01
23914 2023-06-14    0.1116    556.96 LTN 010129 2029-01-01
...
23920 2023-06-22    0.1085    567.02 LTN 010129 2029-01-01
23921 2023-06-23    0.1086    566.97 LTN 010129 2029-01-01

## função get.matur
get.matur <- function(titulo, titulo.td) {

    titulo.td <- data.frame(titulo.td)
    
    ## colocar coluna no formato date
    titulo.td$ref.date <- as.Date(titulo.td$ref.date)

    ## verificar se a data de hoje é dia útil e não feriado
    hoje <- as.Date(Sys.Date())
    
    ## importante saber o fechamento no dia anterior
    ## para tal é necessário saber se é um diz útil
    ## adjust.date:
    ## rolls the given date to the next or previous business day, unless it is a business day.
    ## ou seja, retorna a data do dia útil prévio caso seja sábado, domingo ou feriado usando preceding(dates, cal)
    ## ou do dia corrente (atual).
    dia.util.anterior.ou.hoje <- as.Date(last(titulo.td$ref.date))

    ## selecionar maturidades já emitidas
    message("Selecao de maturidades emitidas para o titulo selecionado.")
    maturidades.validas <- titulo.td %>% filter(as.Date(titulo.td$matur.date) >= as.Date(lubridate::floor_date(Sys.Date(), unit = "year")))
    
    ## valor de cada maturidade válida hoje
    message("Valor de cada maturidade válida hoje.")
    maturidades.validas <- maturidades.validas %>% filter(as.Date(maturidades.validas$ref.date) == as.Date(dia.util.anterior.ou.hoje))

    message("Formatando o valor do yield.")
    maturidades.validas$yield.bid <- format(round(maturidades.validas$yield.bid*100, 4), nsmall = 4)
    
    return(maturidades.validas)
    
}
 
Agradeço qualquer retorno.

André Luiz

**Comment by msperlin** [comment]
Oi André, 

Só hoje fui olhar este issue. Chegaste a resolver? Notei que fechaste o issue.

**Comment by msperlin** [comment]
Aproveitando, não sei qual a fonte dos títulos disponíveis que estás olhando, mas o código busca os dados no repositório de arquivos do TD, e não do site. 

Caso tenha uma sugestão de código, podes adicionar como PR (pull request), por favor? Eu posso avaliar assim que tiver um tempo.

**Comment by andreltr** [comment]
Prezado Marcelo,

**Comment by andreltr** [comment]
Prezado,

Em primeiro lugar, eu gostaria de salientar que cometi um erro no post, pois não havia percebido que o LTN 2033 é com juros semestrais e foi calculado como LTN sem juros semestrais.

Uma sugestão de código seria para incluir o RENDA+ num contexto de análise tipo o disponível em:

https://www.tesourodireto.com.br/rendamais/

**Comment by msperlin** [comment]
Ok, vou averiguar se os dados existem lá. O ideal é abrir um novo issue (vou fazer).
