### ISSUE TITLE
download.TD.data não esta funcionando

### ISSUE THREAD

**Issue by rafaelgouvea** [msperlin/GetTDData#4]
Prezado Marcelo, desde ontem, 02/02/2022, que a função download.TD.data parou de funcionar, retornando o erro abaixo. Saberia dizer se é temporário ou realmente o Tesouro mudou algo em seu repositório que afetou o pacote e demandará atualização ao mesmo?

**Error in utils::download.file(url = i.link, method = "internal", mode = "wb",  : 
  cannot open URL 'http://sisweb.tesouro.gov.br/apex/cosis/sistd/obtem_arquivo/483:103948'
In addition: Warning messages:

In utils::download.file(url = i.link, method = "internal", mode = "wb",  :
  cannot open URL 'http://sisweb.tesouro.gov.br/apex/cosis/sistd/obtem_arquivo/483:103948': HTTP status was '404 Not Found'**

Desde já agradeço.
Atenciosamente, 
Rafael Souza.

**Comment by Lvitor** [comment]
Prezado Marcelo, mesmo erro do colega Rafael. 

Obrigado.

**Comment by msperlin** [comment]
Now fixed in in #5

**Comment by rafaelgouvea** [comment]
> Now fixed in in #5

Olá, Marcelo. 

Testei após os últimos updates de correção e realmente esta fazendo os downloads das planilhas. 

Contudo, essas planilhas estão vindo com os dados dos títulos atualizados apenas até a data de 12/JAN/2022, enquanto que as planilhas no site do Tesouro (https://www.tesourodireto.com.br/titulos/historico-de-precos-e-taxas.htm) estão com os preços atualizados até hoje (10/FEV).

**Comment by msperlin** [comment]
Oi Rafael, 

Reabri o issue e vou dar uma olhada assim q puder.

**Comment by msperlin** [comment]
Arrumado na versão 1.4.3 
Já encaminhei para o CRAN, deve atualizar logo. Podes pegar a versão atual na main branch.,
