### ISSUE TITLE
Erro ao baixar NTN-B Principal

### ISSUE THREAD

**Issue by Vergiel-a** [msperlin/GetTDData#9]
Ao realizar o procedimento de download da NTN-B Principal utilizando o seguinte código:

```
GetTDData::download.TD.data('NTN-B Principal', dl.folder = 'TD Files')

df <- read.TD.files(dl.folder = "TD Files", asset.codes = "NTN-B Principal",
                    maturity = c("150824", "150826", "150535", "150545"))
```
Na função read.TD.files é retornado o seguinte erro:

`Reading xls data and saving to data.frameError in as.Date.default(sapply(my.df$asset.code, my.fct), origin = "1970-01-01") : 
  do not know how to convert 'sapply(my.df$asset.code, my.fct)' to class “Date”`

Este erro não ocorre ao utilizar outro títulos. O que está ocorrendo?

**Comment by msperlin** [comment]
Oi Vergiel, arrumei o bug na última atualização (eb7f0cdf29d77a0d9024a6a6e70bc3259f4060d4). Para simplificar, os argumentos asset.codes e maturity foram retirados da função read.TD.files().
